# Generated by Django 4.0.4 on 2022-04-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'PRODUCTO',
            },
        ),
    ]
